ECHO OFF

REM # Set environment variables 
set FOD_URL="https://api.ams.fortify.com/"
SET FOD_CLIENT_ID=
SET FOD_CLIENT_SECRET=
SET FOD_USER=
SET FOD_PASSWORD=
SET FOD_TENANT=

REM # Entitlement Id is available at https://ams.fortify.com/Admin/Entitlements
SET FOD_ENTITLEMENT_ID=

SET FOD_NEW_APPLICATION=
SET FOD_NEW_APPLICATION_RELEASE=

SET FOD_APPLICATION=
SET FOD_RELEASE=
SET FOD_RELEASE_ID=

SET DEBRICKED_PAT=
SET DEBRICKED_OSS_REPO=
SET DEBRICKED_OSS_BRANCH=
SET FOD_DEBRICKED_IMPORT_TARGET_RELEASE_ID=

SET GIT_REPO=https://github.com/fortify/IWA-Java.git
SET GIT_BRANCH=main