ECHO OFF

REM # Set environment variables 

SET FOD_CLIENT_ID=
SET FOD_CLIENT_SECRET=
SET FOD_USER=
SET FOD_PASSWORD=
SET FOD_TENANT=

REM # Entitlement Id is available at https://ams.fortify.com/Admin/Entitlements
SET FOD_ENTITLEMENT_ID=

SET FOD_NEW_APPLICATION=
SET FOD_NEW_APPLICATION_RELEASE=

SET FOD_APPLICATION=
SET FOD_RELEASE=
SET FOD_RELEASE_ID=