ECHO OFF

REM # Set environment variables 
SET SSC_URL=
SET SC_SAST_SENSOR_VERSION=
SET SC_SAST_CLIENT_TOKEN=

SET SSC_USER=
SET SSC_PASSWORD=

SET SSC_TOKEN=
SET SC_SAST_TOKEN=
SET SSC_CI_TOKEN=

SET SSC_NEW_APPLICATION=
SET SSC_NEW_APPLICATION_VERSION=

SET SSC_APPLICATION=
SET SSC_APPLICATION_VERSION=
SET SSC_APPLICATION_VERSION_ID=
