ECHO OFF

REM # Set environment variables 
SET SSC_URL=
SET SC_SAST_URL=
SET SC_SAST_SENSOR_VERSION=
SET SC_SAST_CLIENT_TOKEN=
REM SET SCANCENTRAL_VM_OPTS=-Dclient_auth_token=%SC_SAST_CLIENT_TOKEN% -Drestapi_connect_timeout=10000

SET SSC_USER=
SET SSC_PASSWORD=

SET SSC_TOKEN=
SET SC_SAST_TOKEN=
SET SSC_CI_TOKEN=

SET SSC_NEW_APPLICATION_NAME=
SET SSC_NEW_VERSION_NAME=

SET SSC_APPLICATION_NAME=
SET SSC_VERSION_NAME=
SET SSC_VERSION_ID=
